// ---------------------------------------------------------------------
// <auto-generated>
// 
// This file has been automatically generated.
// 
// Any changes to it will be lost upon regeneration.
// 
// Consider extending partial classes in ManualExtensions folder.
// 
// </auto-generated>
// ---------------------------------------------------------------------

namespace UnityEngine.AI
{
    [Unity.Burst.BurstCompile]
    public unsafe partial class CooldownDecorator : HiraBotsDecoratorBlackboardFunction
    {
        private struct Memory
        {
            internal System.Boolean _invert;
            internal ushort _globalTime;
            internal ushort _lastExecutionTime;
            internal System.Single _cooldownTimer;
        }

        [SerializeField] internal System.Boolean invert;
        [SerializeField] internal BlackboardTemplate.KeySelector globalTime;
        [SerializeField] internal BlackboardTemplate.KeySelector lastExecutionTime;
        [SerializeField] internal System.Single cooldownTimer;

        // pack memory
        private Memory memory => new Memory
        { _invert = invert, _globalTime = globalTime.selectedKey.offset, _lastExecutionTime = lastExecutionTime.selectedKey.offset, _cooldownTimer = cooldownTimer };

        #region Execution

        // actual function
        [Unity.Burst.BurstCompile(DisableDirectCall = true), AOT.MonoPInvokeCallback(typeof(Delegate))]
        private static bool ActualFunction(in BlackboardComponent.LowLevel blackboard, byte* rawMemory)
        {
            var memory = (Memory*) rawMemory;
            return AIEngineTest.BlackboardFunctions.CooldownDecorator(memory->_invert, ref blackboard.Access<float>(memory->_globalTime), ref blackboard.Access<float>(memory->_lastExecutionTime), memory->_cooldownTimer);
        }

        // non-VM execution
        protected override bool ExecuteFunction(BlackboardComponent blackboard, bool expected)
        {
            var _globalTime = blackboard.GetFloatValue(globalTime.selectedKey.name); var _lastExecutionTime = blackboard.GetFloatValue(lastExecutionTime.selectedKey.name); var output = AIEngineTest.BlackboardFunctions.CooldownDecorator(invert, ref _globalTime, ref _lastExecutionTime, cooldownTimer); return output;
        }

        #endregion

        #region Compilation

        private static bool s_ActualFunctionCompiled = false;
        private static Unity.Burst.FunctionPointer<Delegate> s_ActualFunction;

        public override void PrepareForCompilation()
        {
            base.PrepareForCompilation();
            m_MemorySize += sizeof(Memory); // this will also help make sure the packed memory stays unmanaged

            if (!s_ActualFunctionCompiled)
            {
                s_ActualFunction = Unity.Burst.BurstCompiler.CompileFunctionPointer<Delegate>(ActualFunction);
                s_ActualFunctionCompiled = true;
            }

            functionPtr = s_ActualFunction.Value;
        }

        // compile override
        public override void Compile(ref byte* stream)
        {
            CompilationRegistry.IncreaseDepth();

            var start = stream;

            base.Compile(ref stream);

            *(Memory*) stream = memory;
            stream += sizeof(Memory);

            CompilationRegistry.AddEntry(name, start, stream);

            CompilationRegistry.DecreaseDepth();
        }

        #endregion

#if UNITY_EDITOR
        #region EditorOnlyInterface

        protected override void OnTargetBlackboardTemplateChanged(BlackboardTemplate template, in BlackboardTemplate.KeySet keySet)
        {
            globalTime.OnTargetBlackboardTemplateChanged(template, in keySet); 
            lastExecutionTime.OnTargetBlackboardTemplateChanged(template, in keySet);
        }

        protected override void OnValidateCallback()
        {
            globalTime.keyTypesFilter = UnityEngine.AI.BlackboardKeyType.Invalid | UnityEngine.AI.BlackboardKeyType.Float;
            lastExecutionTime.keyTypesFilter = UnityEngine.AI.BlackboardKeyType.Invalid | UnityEngine.AI.BlackboardKeyType.Float;
            // no external validator
        }

        protected override void UpdateDescription(out string staticDescription)
        {
            AIEngineTest.BlackboardFunctions.CooldownDecoratorUpdateDescription(invert, globalTime, lastExecutionTime, cooldownTimer, out staticDescription);
        }

        #endregion
#endif

#if UNITY_EDITOR || HIRA_BOTS_TESTS || ENABLE_HIRA_BOTS_RUNTIME_BUILDER
        #region Validation

        public override void Validate(ref ValidatorContext context)
        {
            base.Validate(ref context);
            ValidateKeySelector(ref globalTime, UnityEngine.AI.BlackboardKeyType.Invalid | UnityEngine.AI.BlackboardKeyType.Float, ref context, nameof(globalTime));
            ValidateKeySelector(ref lastExecutionTime, UnityEngine.AI.BlackboardKeyType.Invalid | UnityEngine.AI.BlackboardKeyType.Float, ref context, nameof(lastExecutionTime));
        }

        #endregion
#endif
    }
}